services:
  - type: web
    name: job-finder-llm
    env: python
    plan: free
    buildCommand: "./render-build.sh && pip install -r requirements.txt"
    startCommand: "uvicorn src.main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: LINKEDIN_EMAIL
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false
      - key: DEBUG_MODE
        sync: false 